import 'package:flutter/material.dart';

/// Maps icon name strings (stored in database) to Material Icons.
IconData iconFromName(String name) {
  const map = <String, IconData>{
    'shopping_cart': Icons.shopping_cart,
    'home': Icons.home,
    'sports_esports': Icons.sports_esports,
    'restaurant': Icons.restaurant,
    'directions_car': Icons.directions_car,
    'favorite': Icons.favorite,
    'work': Icons.work,
    'category': Icons.category,
    'local_grocery_store': Icons.local_grocery_store,
    'flight': Icons.flight,
    'school': Icons.school,
    'pets': Icons.pets,
    'savings': Icons.savings,
    'child_care': Icons.child_care,
    'fitness_center': Icons.fitness_center,
    'movie': Icons.movie,
    'music_note': Icons.music_note,
    'phone': Icons.phone,
    'wifi': Icons.wifi,
    'attach_money': Icons.attach_money,
    'receipt': Icons.receipt,
    'card_giftcard': Icons.card_giftcard,
    'local_cafe': Icons.local_cafe,
    'local_bar': Icons.local_bar,
    'local_hospital': Icons.local_hospital,
    'local_gas_station': Icons.local_gas_station,
    'train': Icons.train,
    'directions_bus': Icons.directions_bus,
    'directions_bike': Icons.directions_bike,
    'electric_bolt': Icons.electric_bolt,
    'water_drop': Icons.water_drop,
    'checkroom': Icons.checkroom,
    'shopping_bag': Icons.shopping_bag,
    'smartphone': Icons.smartphone,
    'laptop': Icons.laptop,
    'tv': Icons.tv,
    'subscriptions': Icons.subscriptions,
    'book': Icons.book,
    'menu_book': Icons.menu_book,
    'brush': Icons.brush,
    'park': Icons.park,
    'hiking': Icons.hiking,
    'sports_soccer': Icons.sports_soccer,
    'self_improvement': Icons.self_improvement,
    'spa': Icons.spa,
    'medication': Icons.medication,
    'healing': Icons.healing,
    'baby_changing_station': Icons.baby_changing_station,
    'elderly': Icons.elderly,
    'volunteer_activism': Icons.volunteer_activism,
    'construction': Icons.construction,
    'build': Icons.build,
    'cleaning_services': Icons.cleaning_services,
    'pets_outlined': Icons.pets_outlined,
    'forest': Icons.forest,
    'beach_access': Icons.beach_access,
    'event': Icons.event,
    'celebration': Icons.celebration,
    'cookie': Icons.cookie,
    'fastfood': Icons.fastfood,
    'local_pizza': Icons.local_pizza,
    'icecream': Icons.icecream,
    'wine_bar': Icons.wine_bar,
    'eco': Icons.eco,
    'redeem': Icons.redeem,
    'payments': Icons.payments,
    'account_balance': Icons.account_balance,
    'sell': Icons.sell,
    'inventory_2': Icons.inventory_2,
    'dashboard': Icons.dashboard,
    'security': Icons.security,
    'public': Icons.public,
    'language': Icons.language,
    'photo_camera': Icons.photo_camera,
    'camera_roll': Icons.camera_roll,
    'theaters': Icons.theaters,
    'toys': Icons.toys,
    'psychology': Icons.psychology,
  };
  return map[name] ?? Icons.category;
}

/// Available icon names for category creation UI.
const availableIconNames = [
  'shopping_cart',
  'home',
  'sports_esports',
  'restaurant',
  'directions_car',
  'favorite',
  'work',
  'category',
  'local_grocery_store',
  'flight',
  'school',
  'pets',
  'savings',
  'child_care',
  'fitness_center',
  'movie',
  'music_note',
  'phone',
  'attach_money',
  'receipt',
  'local_cafe',
  'local_bar',
  'local_hospital',
  'local_gas_station',
  'wifi',
  'train',
  'directions_bus',
  'directions_bike',
  'electric_bolt',
  'water_drop',
  'checkroom',
  'shopping_bag',
  'smartphone',
  'laptop',
  'tv',
  'subscriptions',
  'book',
  'menu_book',
  'brush',
  'park',
  'hiking',
  'sports_soccer',
  'self_improvement',
  'spa',
  'medication',
  'healing',
  'baby_changing_station',
  'elderly',
  'volunteer_activism',
  'construction',
  'build',
  'cleaning_services',
  'pets_outlined',
  'forest',
  'beach_access',
  'event',
  'celebration',
  'cookie',
  'fastfood',
  'local_pizza',
  'icecream',
  'wine_bar',
  'eco',
  'redeem',
  'payments',
  'account_balance',
  'sell',
  'inventory_2',
  'dashboard',
  'security',
  'public',
  'language',
  'photo_camera',
  'camera_roll',
  'theaters',
  'toys',
  'psychology',
];

/// Available colors for category creation.
const availableCategoryColors = [
  0xFF4CAF50, // Green
  0xFF2196F3, // Blue
  0xFFFF9800, // Orange
  0xFFE91E63, // Pink
  0xFF9C27B0, // Purple
  0xFFF44336, // Red
  0xFF607D8B, // Blue Grey
  0xFF795548, // Brown
  0xFF00BCD4, // Cyan
  0xFFFFEB3B, // Yellow
  0xFF3F51B5, // Indigo
  0xFF009688, // Teal
];
