name: Build Web

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.x"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test

      - name: Build Web
        run: flutter build web --release

      - uses: actions/upload-artifact@v7
        with:
          name: web-release
          path: build/web/
